# Docker Compose file for Family Wiki development environment
# Note: 'version' field is obsolete in Docker Compose V2 and has been removed

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: family_wiki
      POSTGRES_USER: family_wiki_user
      POSTGRES_PASSWORD: family_wiki_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U family_wiki_user -d family_wiki"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    network_mode: host
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    image: family-wiki-web:latest
    ports:
      - "5000:5000"
    environment:
      # Flask configuration
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      
      # Database configuration
      DATABASE_URL: postgresql://family_wiki_user:family_wiki_password@localhost:5432/family_wiki
      
      # Celery configuration
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://localhost:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://localhost:6379/0}
      
      # Ollama configuration - external machine
      OLLAMA_HOST: ${OLLAMA_HOST:-192.168.1.234}  # Can be overridden via .env
      OLLAMA_PORT: ${OLLAMA_PORT:-11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-aya:35b-23}
      
      # Additional configuration
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      WTF_CSRF_ENABLED: ${WTF_CSRF_ENABLED:-True}
    network_mode: host
    volumes:
      # Bind mount for development - changes reflect immediately
      - .:/app
      # Preserve node_modules and .venv if they exist
      - /app/node_modules
      - /app/.venv
      # Create volume for uploaded files
      - app_uploads:/app/web_app/pdf_processing/pdfs
      - app_extracted:/app/web_app/pdf_processing/extracted_text
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "./docker/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Enable TTY for interactive debugging
    tty: true
    stdin_open: true

  celery-worker:
    build: .
    image: family-wiki-web:latest
    command: celery -A web_app.tasks.celery_app worker --loglevel=info
    environment:
      # Database configuration
      DATABASE_URL: postgresql://family_wiki_user:family_wiki_password@localhost:5432/family_wiki
      
      # Celery configuration
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://localhost:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://localhost:6379/0}
      
      # Ollama configuration - external machine
      OLLAMA_HOST: ${OLLAMA_HOST:-192.168.1.234}
      OLLAMA_PORT: ${OLLAMA_PORT:-11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-aya:35b-23}
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.venv
      - app_uploads:/app/web_app/pdf_processing/pdfs
      - app_extracted:/app/web_app/pdf_processing/extracted_text
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  app_uploads:
    driver: local
  app_extracted:
    driver: local
