# Exclude files/directories from linting
exclude = [
    ".git",
    ".pytest_cache", 
    ".venv",
    "__pycache__",
    "web_app/pdf_processing/pdfs",
    "web_app/pdf_processing/extracted_text",
]

# Target Python 3.12
target-version = "py312"

# Set max line length
line-length = 100

[lint]
# Enable specific rule categories
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings  
    "F",    # pyflakes (import issues, undefined vars, etc.)
    "I",    # isort (import sorting)
    "N",    # pep8-naming
    "UP",   # pyupgrade (modern Python syntax)
    "B",    # flake8-bugbear (common bugs)
    "C4",   # flake8-comprehensions
]

# Ignore specific rules
ignore = [
    "E501",  # line too long (handled by line-length setting)
    "B008",  # function calls in argument defaults (common in Click)
    "N999",  # invalid module name (for scripts)
]

[lint.per-file-ignores]
# Test files can have longer names and other conventions
"tests/*" = ["N802", "N803"]
# Scripts can have different naming conventions  
"*_cli.py" = ["N999"]

[lint.isort]
# Group imports
force-single-line = false
lines-after-imports = 2