"""Remove is_active column from extraction_prompts

Revision ID: 3a08ecab2a05
Revises: 578e7d5bf387
Create Date: 2025-07-26 09:00:51.921637

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3a08ecab2a05'
down_revision = '578e7d5bf387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_prompts', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
