"""Add prompt_type and template_variables to extraction_prompts

Revision ID: 578e7d5bf387
Revises: 964273f9af58
Create Date: 2025-07-26 09:00:10.418821

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '578e7d5bf387'
down_revision = '964273f9af58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_type', sa.String(length=50), nullable=False, server_default='extraction'))
        batch_op.add_column(sa.Column('template_variables', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_prompts', schema=None) as batch_op:
        batch_op.drop_column('template_variables')
        batch_op.drop_column('prompt_type')

    # ### end Alembic commands ###
