"""Initial migration with gedcom_id column

Revision ID: 804c62019e8c
Revises: 
Create Date: 2025-07-24 13:46:31.129890

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '804c62019e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', postgresql.UUID(as_uuid=True), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_file_page'), type_='unique')
        batch_op.create_index('idx_ocr_batch', ['batch_id'], unique=False)
        batch_op.create_unique_constraint('unique_batch_file', ['batch_id', 'filename'])

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gedcom_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('sex')
        batch_op.drop_column('gedcom_id')

    with op.batch_alter_table('ocr_pages', schema=None) as batch_op:
        batch_op.drop_constraint('unique_batch_file', type_='unique')
        batch_op.drop_index('idx_ocr_batch')
        batch_op.create_unique_constraint(batch_op.f('unique_file_page'), ['filename', 'page_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
