"""Add raw_content and processing_status to TextCorpus

Revision ID: 964273f9af58
Revises: 804c62019e8c
Create Date: 2025-07-25 18:22:16.861154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964273f9af58'
down_revision = '804c62019e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_corpora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_corpora', schema=None) as batch_op:
        batch_op.drop_column('processing_error')
        batch_op.drop_column('processing_status')
        batch_op.drop_column('raw_content')

    # ### end Alembic commands ###
